"""Initial schema

Revision ID: 6ca660ffd627
Revises: 
Create Date: 2026-08-29 23:07:18.337084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ca660ffd627'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('input_price_per_1k', sa.Float(), nullable=False),
    sa.Column('output_price_per_1k', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_pricing'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workspaces_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('base', 'reference', name='documentrole', native_enum=False), nullable=False),
    sa.Column('source_type', sa.Enum('upload', 'url', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('minio_raw_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'parsed', 'indexed', 'failed', name='documentstatus', native_enum=False), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('doc_language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_documents_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='workspacerole', native_enum=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_members_user_id_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_members_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members')),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member')
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('base_document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'indexing', 'extracting_claims', 'building_context', 'ready', 'failed', name='analysisstatus', native_enum=False), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_document_id'], ['documents.id'], name=op.f('fk_analyses_base_document_id_documents')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_analyses_created_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_analyses_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_table('document_indexes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('minio_index_path', sa.String(), nullable=False),
    sa.Column('coverage_pct', sa.Float(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('built_at', sa.DateTime(), nullable=False),
    sa.Column('enrichment_status', sa.Enum('skeleton_only', 'glossary_done', 'visuals_captioned', 'full', name='enrichmentstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_indexes_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_indexes')),
    sa.UniqueConstraint('document_id', name=op.f('uq_document_indexes_document_id'))
    )
    op.create_table('analysis_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_analysis_references_analysis_id_analyses')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_analysis_references_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_references')),
    sa.UniqueConstraint('analysis_id', 'document_id', name='uq_analysis_reference')
    )
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.Enum('statistic', 'causal', 'comparison', 'quote', 'definition', 'prediction', 'other', name='claimtype', native_enum=False), nullable=False),
    sa.Column('source_node_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('extracted', 'context_built', 'substantiated', 'needs_review', name='claimstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_claims_analysis_id_analyses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_table('trace_spans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='spanstatus', native_enum=False), nullable=False),
    sa.Column('input_ref', sa.String(), nullable=True),
    sa.Column('output_ref', sa.String(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_trace_spans_analysis_id_analyses')),
    sa.ForeignKeyConstraint(['parent_span_id'], ['trace_spans.id'], name=op.f('fk_trace_spans_parent_span_id_trace_spans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trace_spans'))
    )
    op.create_table('claim_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('local_node_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('structural_node_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('global_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_trace_id', sa.UUID(), nullable=True),
    sa.Column('context_sufficient', sa.Boolean(), nullable=False),
    sa.Column('built_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_trace_id'], ['trace_spans.id'], name=op.f('fk_claim_contexts_agent_trace_id_trace_spans')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_contexts_claim_id_claims')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_contexts')),
    sa.UniqueConstraint('claim_id', name=op.f('uq_claim_contexts_claim_id'))
    )
    op.create_table('reference_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('shortlisted', 'checked', 'skipped', name='referencemappingstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_reference_mappings_claim_id_claims')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_reference_mappings_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_mappings'))
    )
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('span_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('called_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['span_id'], ['trace_spans.id'], name=op.f('fk_tool_calls_span_id_trace_spans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls'))
    )
    op.create_table('verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('issue', sa.Text(), nullable=True),
    sa.Column('evidence_node_id', sa.String(), nullable=True),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='confidencelevel', native_enum=False), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_verifications_claim_id_claims')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_verifications_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verifications'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verifications')
    op.drop_table('tool_calls')
    op.drop_table('reference_mappings')
    op.drop_table('claim_contexts')
    op.drop_table('trace_spans')
    op.drop_table('claims')
    op.drop_table('analysis_references')
    op.drop_table('document_indexes')
    op.drop_table('analyses')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('model_pricing')
    # ### end Alembic commands ###
